### PR TITLE
Global project update/organizing

### PR DESCRIPTION
**Pull request by AmiDARK**
- Changed the place where the configuration are copied at compilation time (moved them to AMOS/S)
- Changed a place where AMOS.library was copied at compilation time (to AMOS/Libs)
- Moved the concerned files to place where they should be.

### CODE REVIEW

**Comment by marc365** [comment]
looks good - sorry I missed this, only just picked up the email, can
we do a branch to merge this to first?

**Comment by AmiDARK** [comment]
Hello Marc,
Happy to hear news from you.
 
I was obliged to makes temporarly the changes I've made (and I 'm continuying to make) private due to problems with François Lionet.
(he wanted to create a new Boxed version of Amos Professional containing unfinished AGA Support I'm making at a price that is definitively too high in my point of view ( ~200€ ), that's why I changed my repo to private to be sure he don't use my changes without my agreements as he said me "With or without you, I'll sell an AGA Version of Amos Professional, now you shown me it's possible, I can do it myself if needed".
Due to that, the merge I previously sent to your repo was cancelled (it's not your fault).
Once I'll have finished the AGA support and that a full package (for free) will be prepared with licence (to protect me against any commercial use from François Lionet without my agreements), I will probably open source code again for "educationnal" purposes because I adding several comments to explain how Amos Professional internally work.
You can see my Youtube channel playlist 'Amos Professional X' to view all changes that are released in the public build/release repository :
https://www.youtube.com/watch?v=aoC9JODHT-Q&list=PL6Q17EL65z6Egqoo1Zaphlvds0LxS2RHV
 
The official public releases repository is here if you want to see WIP AGA Support : https://github.com/AmiDARK/AmosProfessionalX-Releases
 
Be sure that when I'll release source code again, I will propose you again to merge change with your Amos Professional GIT repository..
 
Best regards,
Frédéric Cordier Aka AmiDARK.
 
> Message du 09/12/19 10:52> De : "marc365" > A : "marc365/AMOSProfessional" > Copie à : "Frédéric Cordier" , "State change" > Objet : Re: [marc365/AMOSProfessional] Global project update/organizing (#2)> > looks good - sorry I missed this, only just picked up the email, can> we do a branch to merge this to first?>
—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/marc365/AMOSProfessional/pull/2?email_source=notifications\u0026email_token=ACNMEG7ZVHIWZJQH22DZEKTQXYIMRA5CNFSM4JQWFWW2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGIQK2A#issuecomment-563152232", "url": "https://github.com/marc365/AMOSProfessional/pull/2?email_source=notifications\u0026email_token=ACNMEG7ZVHIWZJQH22DZEKTQXYIMRA5CNFSM4JQWFWW2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGIQK2A#issuecomment-563152232", "name": "View Pull Request" }, "description": "View this Pull Request on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by marc365** [comment]
hey :)
very nice, i'm very impressed and excited to hear from you - I have
just caught up with your project(s) wow. I give you my full support,
I'll catch up a bit more and get involved.
I see the apollo mentioned on the yt posts, which is great, I have the
noAMOS.library ready and waiting for them...

I don't want to add too much about Francois but he did a seem
"personally affected" regarding the Amiga version - there is a history
for him that he has to resolve, which I think also interferes with
everyone on the "scene" a bit - for myself wokring on this was a
history lession - digital archeology maybe - it was something that
affected me as a child, so yes personal as well :) I've done similar
work to the Amiga OS 3.1 source leak but can't talk about that in
public - but it's very interesting how the two histories collide.
Francois was a registered Commodore developer so had access to the
internal information and tools from them, which he doesn't have to
fall back on any more and maybe knowns less than you do - I think he
uses my build base with the ASM ONE header files, that's great but he
seems underhanded with it even though it is open for anyone to start
working with.

I'll find some time to have a play with your release and get back to
you soon.

Best Regards,

Marc
 Sent using Hushmail
On 09/12/2019 at 10:01 AM, "Frédéric Cordier"  wrote:Hello Marc,
 Happy to hear news from you.
 I was obliged to makes temporarly the changes I've made (and I 'm
continuying to make) private due to problems with François Lionet.
 (he wanted to create a new Boxed version of Amos Professional
containing unfinished AGA Support I'm making at a price that is
definitively too high in my point of view ( ~200€ ), that's why I
changed my repo to private to be sure he don't use my changes without
my agreements as he said me "With or without you, I'll sell an AGA
Version of Amos Professional, now you shown me it's possible, I can do
it myself if needed".
 Due to that, the merge I previously sent to your repo was cancelled
(it's not your fault).
 Once I'll have finished the AGA support and that a full package (for
free) will be prepared with licence (to protect me against any
commercial use from François Lionet without my agreements), I will
probably open source code again for "educationnal" purposes because I
adding several comments to explain how Amos Professional internally
work.
 You can see my Youtube channel playlist 'Amos Professional X' to view
all changes that are released in the public build/release repository :
 https://www.youtube.com/watch?v=aoC9JODHT-Q&list=PL6Q17EL65z6Egqoo1Zaphlvds0LxS2RHV
 The official public releases repository is here if you want to see
WIP AGA Support :
https://github.com/AmiDARK/AmosProfessionalX-Releases
 Be sure that when I'll release source code again, I will propose you
again to merge change with your Amos Professional GIT repository..
 Best regards,
 Frédéric Cordier Aka AmiDARK.
 > Message du 09/12/19 10:52> De : "marc365" > A :
"marc365/AMOSProfessional" > Copie à : "Frédéric Cordier" , "State
change" > Objet : Re: [marc365/AMOSProfessional] Global project
update/organizing (#2)> > looks good - sorry I missed this, only just
picked up the email, can> we do a branch to merge this to first?>
 —You are receiving this because you modified the open/close
state.Reply to this email directly, view it on GitHub, or unsubscribe.
 [ { "@context": "http://schema.org", "@type": "EmailMessage",
"potentialAction": { "@type": "ViewAction", "target":
"https://github.com/marc365/AMOSProfessional/pull/2?email_source=notificationsu0026email_token=ACNMEG7ZVHIWZJQH22DZEKTQXYIMRA5CNFSM4JQWFWW2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGIQK2A#issuecomment-563152232";,
"name": "View Pull Request" }, "description": "View this Pull Request
on GitHub", "publisher": { "@type": "Organization", "name": "GitHub",
"url": "https://github.com" } } ]

**Comment by AmiDARK** [comment]
Hi :)
 
Thank you for your reply.
 
And, Yes. I confirm that concerning what you think about François when you said "seem "personally affected" regarding the Amiga version".
I think the same about him adding that he can be emotionnally unstable (or simulate this ?).
There are grey parts of his past that are not exactly what he say (I remind someone from ClickTeam coming to his page reminding him that something he reproached to ClickTeam was in fact his fault (and not ClickTeam one) .. He apologized about this confirming that, his judgment about facts, reality and things is sometimes not objective (altered ?)
But I prefer thinking that even with his foolish look, he is someone good.
 
Regards,
Frederic.
> Message du 09/12/19 11:59> De : "marc365" > A : "marc365/AMOSProfessional" > Copie à : "Frédéric Cordier" , "State change" > Objet : Re: [marc365/AMOSProfessional] Global project update/organizing (#2)> > hey :)> very nice, i'm very impressed and excited to hear from you - I have> just caught up with your project(s) wow. I give you my full support,> I'll catch up a bit more and get involved.> I see the apollo mentioned on the yt posts, which is great, I have the> noAMOS.library ready and waiting for them...> > I don't want to add too much about Francois but he did a seem> "personally affected" regarding the Amiga version - there is a history> for him that he has to resolve, which I think also interferes with> everyone on the "scene" a bit - for myself wokring on this was a> history lession - digital archeology maybe - it was something that> affected me as a child, so yes personal as well :) I've done similar> work to the Amiga OS 3.1 source leak but can't talk about that in> public - but it's very interesting how the two histories collide.> Francois was a registered Commodore developer so had access to the> internal information and tools from them, which he doesn't have to> fall back on any more and maybe knowns less than you do - I think he> uses my build base with the ASM ONE header files, that's great but he> seems underhanded with it even though it is open for anyone to start> working with.> > I'll find some time to have a play with your release and get back to> you soon.> > Best Regards,> > Marc> Sent using Hushmail> On 09/12/2019 at 10:01 AM, "Frédéric Cordier" wrote:Hello Marc,> Happy to hear news from you.> I was obliged to makes temporarly the changes I've made (and I 'm> continuying to make) private due to problems with François Lionet.> (he wanted to create a new Boxed version of Amos Professional> containing unfinished AGA Support I'm making at a price that is> definitively too high in my point of view ( ~200€ ), that's why I> changed my repo to private to be sure he don't use my changes without> my agreements as he said me "With or without you, I'll sell an AGA> Version of Amos Professional, now you shown me it's possible, I can do> it myself if needed".> Due to that, the merge I previously sent to your repo was cancelled> (it's not your fault).> Once I'll have finished the AGA support and that a full package (for> free) will be prepared with licence (to protect me against any> commercial use from François Lionet without my agreements), I will> probably open source code again for "educationnal" purposes because I> adding several comments to explain how Amos Professional internally> work.> You can see my Youtube channel playlist 'Amos Professional X' to view> all changes that are released in the public build/release repository :> https://www.youtube.com/watch?v=aoC9JODHT-Q&list=PL6Q17EL65z6Egqoo1Zaphlvds0LxS2RHV> The official public releases repository is here if you want to see> WIP AGA Support :> https://github.com/AmiDARK/AmosProfessionalX-Releases> Be sure that when I'll release source code again, I will propose you> again to merge change with your Amos Professional GIT repository..> Best regards,> Frédéric Cordier Aka AmiDARK.> > Message du 09/12/19 10:52> De : "marc365" > A :> "marc365/AMOSProfessional" > Copie à : "Frédéric Cordier" , "State> change" > Objet : Re: [marc365/AMOSProfessional] Global project> update/organizing (#2)> > looks good - sorry I missed this, only just> picked up the email, can> we do a branch to merge this to first?>> —You are receiving this because you modified the open/close> state.Reply to this email directly, view it on GitHub, or unsubscribe.> [ { "@context": "http://schema.org", "@type": "EmailMessage",> "potentialAction": { "@type": "ViewAction", "target":> "https://github.com/marc365/AMOSProfessional/pull/2?email_source=notificationsu0026email_token=ACNMEG7ZVHIWZJQH22DZEKTQXYIMRA5CNFSM4JQWFWW2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGIQK2A#issuecomment-563152232";,> "name": "View Pull Request" }, "description": "View this Pull Request> on GitHub", "publisher": { "@type": "Organization", "name": "GitHub",> "url": "https://github.com" } } ] > > —> You are receiving this because you commented.> Reply to this email directly, view it on GitHub, or unsubscribe.
—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/marc365/AMOSProfessional/pull/2?email_source=notifications\u0026email_token=ACNMEGZWEIFTSU7LZ57NPR3QXYQJZA5CNFSM4JQWFWW2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGIXW3Y#issuecomment-563182447", "url": "https://github.com/marc365/AMOSProfessional/pull/2?email_source=notifications\u0026email_token=ACNMEGZWEIFTSU7LZ57NPR3QXYQJZA5CNFSM4JQWFWW2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGIXW3Y#issuecomment-563182447", "name": "View Pull Request" }, "description": "View this Pull Request on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by AmiDARK** [comment]
Hello Marc,
Francois lionet finally removed the idea to put AmosPRO under LGPLv3 licence.
He also finally create the "Amos Professional Official" source code repository based on your repository and under MIT Licence : https://github.com/Francaoz/AMOS-Professional-Official
You should take a look at it.

Maybe your version with noAMOS.library may now come to live ?

My previous project Amos Professional X will not get revival under "Amos Professional AGA" name.
I concentrate efforts with Amos Factory team so I should integrate my changes to their version when my project will be completed.

Waiting news from you ;)
Regards,

**Comment by mythrill** [comment]
Hi Frédéric,

thanks for letting me know - Francois didn't bother to let me know and it really is an exact copy - the includes and bins are mine lol.

well, at least it worked and got things moving at last and there still seems to be interested devs which is great...

the noAMOS library was used to build all the cli tools, so its kind've in there already :)

on a personal note (without getting negative):

I think the AMOS Factory will be good for helping spreading the word but not sure about their code base - I remeber their programming skill and concepts were quite lacking, but don't get disheartened with their ideas and don't let them hold you back, what you've done is amazing, so don't let Bruce binary hack anything for the release, insist on source code, and don't let Samurai get away with doing nothing and saying everything!!!)

Best Regards,

Marc

**Comment by marc365** [comment]
Hi Frédéric,

thanks for letting me know - Francois didn't bother to let me know and it really is an exact copy - the includes and bins are mine lol.

well, at least it worked and got things moving at last and there still seems to be interested devs which is great...

the noAMOS library was used to build all the cli tools, so its kind've in there already :)

on a personal note (without getting negative):

I think the AMOS Factory will be good for helping spreading the word but not sure about their code base - I remeber their programming skill and concepts were quite lacking, but don't get disheartened with their ideas and don't let them hold you back, what you've done is amazing, so don't let Bruce binary hack anything for the release, insist on source code, and don't let Samurai get away with doing nothing and saying everything!!!)

Best Regards,

Marc

**Comment by AmiDARK** [comment]
Hi,
 
You're right that François did not take care about what he do.
AMOS Factory did some good changes with a developer external to the team.
They fixed some issues in AMOS engine and they do some improvements to the Editor (for example, the use of mouse scroll button for file selectors).
I will probably includes their changes in my AGA version but for the moment, source code is closed due to what happened in the past.
A git hub for binaries (release/beta/alpha) is available.
Git Hub  https://github.com/AmiDARK/Amos-Professional-AGA-Releases
 
And a mini site to keep people informed on my devs is also available.
Here : http://amos-professional-aga.frederic-cordier.fr/
 
Regards,
Fred Aka AmiDARK
 
> Message du 18/05/20 15:50> De : "mythrill" > A : "marc365/AMOSProfessional" > Copie à : "Frédéric Cordier" , "State change" > Objet : Re: [marc365/AMOSProfessional] Global project update/organizing (#2)> >
>
> Hi Frédéric,
> thanks for letting me know - Francois didn't bother to let me know and it really is an exact copy - the includes and bins are mine lol.
> well, at least it worked and got things moving at last and there still seems to be interested devs which is great...
> the noAMOS library was used to build all the cli tools, so its kind've in there already :)
> on a personal note (without getting negative):
> I think the AMOS Factory will be good for helping spreading the word but not sure about their code base - I remeber their programming skill and concepts were quite lacking, but don't get disheartened with their ideas and don't let them hold you back, what you've done is amazing, so don't let Bruce binary hack anything for the release, insist on source code, and don't let Samurai get away with doing nothing and saying everything!!!)
> Best Regards,
> Marc
—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/marc365/AMOSProfessional/pull/2#issuecomment-630196110", "url": "https://github.com/marc365/AMOSProfessional/pull/2#issuecomment-630196110", "name": "View Pull Request" }, "description": "View this Pull Request on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by marc365** [comment]
Hi AmiDark,

I've just seen you've made an update and I'm going to catch up with that. but I also have an update of my branch coming, I need to test a bit more but I have been able to fix a number (if not all) of those serious "systemic" bugs. you know bugs like the compiler crashing, those really horrible ones that make people say AMOS is not system friendly. I'm at the last stage of testing and will pull together a commit as soon as I can. I can forward you a copy if you want to do a diff locally or want to help test/confirm? or maybe your amos doesn't crash? lol. the fixes are really simple, but were hell to trace...

Regards,

Marc

**Pull request closed without merging**
